// Mock data for development and testing

import {
    Product,
    Price,
    CardOffer,
    Review,
    Platform,
    BankName,
    CardType,
} from '../types';

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Apple iPhone 15 Pro (256GB) - Natural Titanium',
        description: 'FORGED IN TITANIUM — iPhone 15 Pro has a strong and light aerospace-grade titanium design with a textured matte glass back.',
        category: 'Electronics',
        brand: 'Apple',
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500&q=80',
    },
    {
        id: '2',
        name: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 256GB)',
        description: 'Meet Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with a new titanium exterior and a 17.25cm flat display.',
        category: 'Electronics',
        brand: 'Samsung',
        imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500&q=80',
    },
    {
        id: '3',
        name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
        description: 'Industry-leading noise cancellation with Auto NC Optimizer, exceptional sound quality with LDAC, and up to 30-hour battery life.',
        category: 'Electronics',
        brand: 'Sony',
        imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500&q=80',
    },
    {
        id: '4',
        name: 'Nike Air Zoom Pegasus 40 Running Shoes',
        description: 'Responsive cushioning in the Pegasus provides an energized ride for everyday road running.',
        category: 'Fashion',
        brand: 'Nike',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    },
    {
        id: '5',
        name: 'Levi\'s Men\'s 511 Slim Fit Jeans',
        description: 'Slim fit jeans that sit below the waist with a slim leg from hip to ankle.',
        category: 'Fashion',
        brand: 'Levi\'s',
        imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&q=80',
    },
    {
        id: '6',
        name: 'Dell XPS 15 Laptop (Intel i7, 16GB RAM, 512GB SSD)',
        description: 'Stunning 15.6-inch OLED display, powerful performance, and premium build quality.',
        category: 'Electronics',
        brand: 'Dell',
        imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&q=80',
    },
];

export const mockPrices: Record<string, Price[]> = {
    '1': [
        {
            platform: Platform.AMAZON,
            productUrl: 'https://www.amazon.in/Apple-iPhone-15-Pro-256GB/dp/B0CHWV2WYK',
            originalPrice: 134900,
            discountedPrice: 129900,
            discount: 3.7,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.FLIPKART,
            productUrl: 'https://www.flipkart.com/apple-iphone-15-pro-natural-titanium-256-gb/p/itm6c9f4d62e0a5f?pid=MOBGTAGPTB3VS24W',
            originalPrice: 134900,
            discountedPrice: 127900,
            discount: 5.2,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.SNAPDEAL,
            productUrl: 'https://www.snapdeal.com/product/apple-iphone-15-pro-256gb/652309874123',
            originalPrice: 134900,
            discountedPrice: 131900,
            discount: 2.2,
            inStock: false,
            lastUpdated: new Date(),
        },
    ],
    '2': [
        {
            platform: Platform.AMAZON,
            productUrl: 'https://www.amazon.in/Samsung-Galaxy-Ultra-Titanium-Gray/dp/B0CS4J295J',
            originalPrice: 124999,
            discountedPrice: 119999,
            discount: 4.0,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.FLIPKART,
            productUrl: 'https://www.flipkart.com/samsung-galaxy-s24-ultra-5g-titanium-gray-256-gb/p/itm2a009d7478540',
            originalPrice: 124999,
            discountedPrice: 117999,
            discount: 5.6,
            inStock: true,
            lastUpdated: new Date(),
        },
    ],
    '3': [
        {
            platform: Platform.AMAZON,
            productUrl: 'https://www.amazon.in/Sony-WH-1000XM5-Wireless-Cancelling-Headphones/dp/B09XS7JWHH',
            originalPrice: 29990,
            discountedPrice: 26990,
            discount: 10.0,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.FLIPKART,
            productUrl: 'https://www.flipkart.com/sony-wh-1000xm5-bluetooth-headset/p/itmef79326e22e3c',
            originalPrice: 29990,
            discountedPrice: 27490,
            discount: 8.3,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.SNAPDEAL,
            productUrl: 'https://www.snapdeal.com/product/sony-wh1000xm5-over-ear-headphones/634892109876',
            originalPrice: 29990,
            discountedPrice: 28990,
            discount: 3.3,
            inStock: true,
            lastUpdated: new Date(),
        },
    ],
    '4': [
        {
            platform: Platform.AMAZON,
            productUrl: 'https://www.amazon.in/Nike-Mens-Pegasus-Running-Shoe/dp/B0C4F6Y8Z9',
            originalPrice: 10795,
            discountedPrice: 8995,
            discount: 16.7,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.MYNTRA,
            productUrl: 'https://www.myntra.com/sports-shoes/nike/nike-men-black-air-zoom-pegasus-40-running-shoes/22876543/buy',
            originalPrice: 10795,
            discountedPrice: 8636,
            discount: 20.0,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.AJIO,
            productUrl: 'https://www.ajio.com/nike-air-zoom-pegasus-40-running-shoes/p/469456789_black',
            originalPrice: 10795,
            discountedPrice: 9175,
            discount: 15.0,
            inStock: true,
            lastUpdated: new Date(),
        },
    ],
    '5': [
        {
            platform: Platform.AMAZON,
            productUrl: 'https://www.amazon.in/Levis-Mens-Slim-Jeans-18298-1148_Blue/dp/B082P3X9X9',
            originalPrice: 3999,
            discountedPrice: 2799,
            discount: 30.0,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.FLIPKART,
            productUrl: 'https://www.flipkart.com/levis-men-slim-mid-rise-blue-jeans/p/itm890123456789',
            originalPrice: 3999,
            discountedPrice: 2599,
            discount: 35.0,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.MYNTRA,
            productUrl: 'https://www.myntra.com/jeans/levis/levis-men-blue-511-slim-fit-stretchable-jeans/11234567/buy',
            originalPrice: 3999,
            discountedPrice: 2699,
            discount: 32.5,
            inStock: true,
            lastUpdated: new Date(),
        },
    ],
    '6': [
        {
            platform: Platform.AMAZON,
            productUrl: 'https://www.amazon.in/Dell-XPS-9530-Laptop-i7-13700H/dp/B0C3456789',
            originalPrice: 159990,
            discountedPrice: 149990,
            discount: 6.3,
            inStock: true,
            lastUpdated: new Date(),
        },
        {
            platform: Platform.FLIPKART,
            productUrl: 'https://www.flipkart.com/dell-xps-15-core-i7-13th-gen-16-gb-512-gb-ssd-windows-11-home-xps-9530-laptop/p/itm123456789012',
            originalPrice: 159990,
            discountedPrice: 152990,
            discount: 4.4,
            inStock: true,
            lastUpdated: new Date(),
        },
    ],
};

const currentYear = new Date().getFullYear();
const endOfYear = new Date(`${currentYear}-12-31`);

export const mockCardOffers: CardOffer[] = [
    {
        id: 'offer-1',
        bank: BankName.HDFC,
        cardType: CardType.CREDIT,
        discountPercentage: 10,
        maxDiscount: 5000,
        minPurchase: 10000,
        description: '10% Instant Discount on HDFC Bank Credit Cards',
        termsAndConditions: `Valid on purchases above ₹10,000. Maximum discount ₹5,000. Valid till 31st Dec ${currentYear}.`,
        validUntil: endOfYear,
        applicablePlatforms: [Platform.AMAZON, Platform.FLIPKART],
    },
    {
        id: 'offer-2',
        bank: BankName.ICICI,
        cardType: CardType.DEBIT,
        discountPercentage: 5,
        maxDiscount: 2000,
        minPurchase: 5000,
        description: '5% Cashback on ICICI Debit Cards',
        termsAndConditions: 'Valid on purchases above ₹5,000. Maximum cashback ₹2,000. Valid on all days.',
        validUntil: endOfYear,
        applicablePlatforms: [Platform.AMAZON, Platform.FLIPKART, Platform.MYNTRA],
    },
    {
        id: 'offer-3',
        bank: BankName.SBI,
        cardType: CardType.CREDIT,
        discountPercentage: 7.5,
        maxDiscount: 3000,
        minPurchase: 15000,
        description: '7.5% Discount on SBI Credit Cards',
        termsAndConditions: 'Valid on electronics. Minimum purchase ₹15,000. Maximum discount ₹3,000.',
        validUntil: endOfYear,
        applicablePlatforms: [Platform.FLIPKART, Platform.SNAPDEAL],
    },
    {
        id: 'offer-4',
        bank: BankName.AXIS,
        cardType: CardType.CREDIT,
        discountPercentage: 12,
        maxDiscount: 4000,
        minPurchase: 20000,
        description: '12% Instant Discount on Axis Bank Credit Cards',
        termsAndConditions: 'Valid on fashion and electronics. Minimum purchase ₹20,000.',
        validUntil: endOfYear,
        applicablePlatforms: [Platform.MYNTRA, Platform.AJIO],
    },
    {
        id: 'offer-5',
        bank: BankName.KOTAK,
        cardType: CardType.DEBIT,
        discountPercentage: 8,
        maxDiscount: 2500,
        minPurchase: 8000,
        description: '8% Cashback on Kotak Debit Cards',
        termsAndConditions: 'Valid on all categories. Minimum purchase ₹8,000. Maximum cashback ₹2,500.',
        validUntil: endOfYear,
        applicablePlatforms: [Platform.AMAZON, Platform.FLIPKART, Platform.SNAPDEAL],
    },
];

export const mockReviews: Record<string, Review[]> = {
    '1': [
        {
            platform: Platform.AMAZON,
            rating: 4.6,
            totalReviews: 12453,
            highlights: ['Excellent camera quality', 'Premium titanium build', 'Great battery life'],
            sentiment: 'positive',
        },
        {
            platform: Platform.FLIPKART,
            rating: 4.5,
            totalReviews: 8932,
            highlights: ['Fast performance', 'Beautiful display', 'iOS ecosystem'],
            sentiment: 'positive',
        },
    ],
    '2': [
        {
            platform: Platform.AMAZON,
            rating: 4.7,
            totalReviews: 15234,
            highlights: ['Amazing S Pen functionality', 'Stunning display', 'Excellent cameras'],
            sentiment: 'positive',
        },
        {
            platform: Platform.FLIPKART,
            rating: 4.6,
            totalReviews: 11245,
            highlights: ['Great for productivity', 'Long battery life', 'Premium design'],
            sentiment: 'positive',
        },
    ],
    '3': [
        {
            platform: Platform.AMAZON,
            rating: 4.8,
            totalReviews: 23456,
            highlights: ['Best noise cancellation', 'Comfortable for long use', 'Excellent sound quality'],
            sentiment: 'positive',
        },
        {
            platform: Platform.FLIPKART,
            rating: 4.7,
            totalReviews: 18932,
            highlights: ['Premium build quality', 'Great for travel', 'Long battery life'],
            sentiment: 'positive',
        },
    ],
    '4': [
        {
            platform: Platform.AMAZON,
            rating: 4.4,
            totalReviews: 5678,
            highlights: ['Comfortable fit', 'Good for daily runs', 'Durable'],
            sentiment: 'positive',
        },
        {
            platform: Platform.MYNTRA,
            rating: 4.3,
            totalReviews: 4321,
            highlights: ['True to size', 'Great cushioning', 'Stylish design'],
            sentiment: 'positive',
        },
    ],
    '5': [
        {
            platform: Platform.AMAZON,
            rating: 4.5,
            totalReviews: 8765,
            highlights: ['Perfect fit', 'Good quality denim', 'Classic style'],
            sentiment: 'positive',
        },
        {
            platform: Platform.FLIPKART,
            rating: 4.4,
            totalReviews: 6543,
            highlights: ['Comfortable', 'Value for money', 'Durable fabric'],
            sentiment: 'positive',
        },
        {
            platform: Platform.MYNTRA,
            rating: 4.6,
            totalReviews: 7890,
            highlights: ['Slim fit as expected', 'Great color options', 'Premium quality'],
            sentiment: 'positive',
        },
    ],
    '6': [
        {
            platform: Platform.AMAZON,
            rating: 4.6,
            totalReviews: 3456,
            highlights: ['Beautiful OLED display', 'Powerful performance', 'Premium build'],
            sentiment: 'positive',
        },
        {
            platform: Platform.FLIPKART,
            rating: 4.5,
            totalReviews: 2345,
            highlights: ['Great for creative work', 'Excellent keyboard', 'Long battery life'],
            sentiment: 'positive',
        },
    ],
};
